hw4 completed
Alexei-Str/AndroidHW pull request #1
Opened 2019-10-26 20:14 UTC by Alexei-Str

2019-10-28 20:10 UTC, NailShaykhrazievItis requested changes

2019-10-28 20:10 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/hw4_intent/MainActivity.kt
> +            startActivityForResult(sendIntent, 1)
1 вынести в константу

2019-10-28 20:10 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/hw4_intent/MainActivity.kt
> +
extra line

2019-10-28 20:10 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/hw4_intent/SecondActivity.kt
> +        textView.text = ""+value
value.toString()

2019-10-28 20:10 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_second.xml
> +        android:id="@+id/textView"
tv_some_semantic or text_some_semantic

2019-10-28 20:10 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/button"
btn_some_semantic or button_some_semantic

2019-10-29 15:49 UTC, Alexei-Str commented
Не совсем понял, зачем приводить value к String, когда в манифесте фильтр mimeType="text/plain",  что подразумевает текстовые данные.

2019-10-29 21:20 UTC, NailShaykhrazievItis approved these changes

2019-10-30 07:22 UTC, closed without merging