HW5
Alexei-Str/AndroidHW pull request #2
Opened 2019-11-02 15:02 UTC by Alexei-Str

ЪуЪ

2019-11-02 15:08 UTC, Alexei-Str commented
![Screenshot_2019-11-02-17-50-09 1](https://user-images.githubusercontent.com/14045147/68072885-b3cfa980-fd9b-11e9-9548-3d010df4cf8c.jpg)
![IMG_20191102_175145 1](https://user-images.githubusercontent.com/14045147/68072888-bf22d500-fd9b-11e9-9c9d-7e478b2d61df.jpg)

2019-11-24 10:57 UTC, NailShaykhrazievItis requested changes

2019-11-24 10:57 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/hw5/Film.kt
> +)
add line after class

2019-11-24 10:57 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/hw5/FilmAdapter.kt
> +        holder.itemView.setOnClickListener { v ->
У тебя адаптер не знает а более высоких слоях абстракции как активити. Он не должен уметь запускать другие экраны. Он умеет биндить разные данные в список.

Посмотри тут как это делается: https://github.com/NailShaykhrazievItis/Template/blob/task/rekyklep/app/src/main/java/com/itis/template/BookAdapter.kt

Единственное лямбда будет такой: private val clickLambda: (Film) -> Unit

2019-11-24 10:57 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/hw5/FilmAdapter.kt
> +    class FilmHolder(itemView: View?) : RecyclerView.ViewHolder(itemView!!) {
!! -1 балл
Вынести в отдельный класс. Имплементировать LayoutContainer. Добавить метод бинд

2019-11-24 10:57 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/hw5/PageActivity.kt
> +        title_text_view.text = intent.getStringExtra("title").toString()
"title", "img", "description" вынести в константы with naming EXTRA_TITLE

2019-11-24 10:57 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/hw5/PageActivity.kt
> +}
add line after class

2019-11-24 10:57 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/hw5/RecyclerView.kt
> +}
add line after class

2019-11-24 10:57 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_detail.xml
> +        android:layout_width="383dp"
Выглядит как хардкод. Если хочешь чтоб на всю ширину экрана была то 0дп. И можно потом отступы прописать marginStart=16dp например. Если эт прям чилсо и не хардкод(хотя это он и есть), то число должно делиться на 4

2019-11-24 10:57 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_detail.xml
> +        android:id="@+id/film_image_view"
iv_film or image_film так проще ищется ресурсы через код. Все id переделать

2019-11-24 10:57 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_detail.xml
> +            android:paddingLeft="5dp"
число должно делиться на 4 по материал дезигну. Или 4 или 8

2019-11-24 10:57 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_detail.xml
> +        android:layout_width="408dp"
делиться на 4 число должно

2019-11-24 10:57 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_recycler.xml
> +
extra line

2019-11-25 12:14 UTC, NailShaykhrazievItis approved these changes

2019-11-25 12:27 UTC, closed without merging